# -*- coding: utf-8 -*-
"""week 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O5aLtQ3T3VSFGONyp0zxQg3InTVIXT_v
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv("placement_dataset.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

display(df.head())

# ==========================================================
# WEEK 2 - DATA VISUALIZATION AND EDA
# ==========================================================

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


# ==========================================================
# 1. LOAD DATASET
# ==========================================================

df = pd.read_csv("placement_dataset.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

display(df.head())


# ==========================================================
# 2. CHECK DATA
# ==========================================================

print("\nCOLUMN NAMES:")
print(df.columns.tolist())

print("\nMISSING VALUES:")
print(df.isnull().sum())


# ==========================================================
# 3. PLACEMENT COUNT BY BRANCH
# ==========================================================

plt.figure(figsize=(6, 4))

sns.countplot(
    data=df,
    x="Branch"
)

plt.title("Placement Count by Branch")
plt.xlabel("Branch")
plt.ylabel("Count")

plt.xticks(rotation=45)

plt.tight_layout()
plt.show()


# ==========================================================
# 4. CGPA DISTRIBUTION
# ==========================================================

plt.figure(figsize=(6, 4))

plt.hist(
    df["CGPA"].dropna(),
    bins=15,
    edgecolor="black"
)

plt.title("CGPA Distribution")
plt.xlabel("CGPA")
plt.ylabel("Frequency")

plt.tight_layout()
plt.show()


# ==========================================================
# 5. CORRELATION HEATMAP
# ==========================================================

plt.figure(figsize=(8, 6))

numeric_df = df.select_dtypes(
    include="number"
)

corr_matrix = numeric_df.corr()

sns.heatmap(
    corr_matrix,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Correlation Heatmap")

plt.tight_layout()
plt.show()


# ==========================================================
# 6. COMPLETED
# ==========================================================

print("\n" + "=" * 50)
print("WEEK 2 ANALYSIS COMPLETED SUCCESSFULLY!")
print("=" * 50)