# -*- coding: utf-8 -*-
"""week 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11qvZp-zHeA6qDjBa8G-rt6yPZpUj2wPg
"""

import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"

df = pd.read_csv(url)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

display(df.head())

df.to_csv("Titanic-Dataset.csv", index=False)

print("Titanic-Dataset.csv created successfully!")

from google.colab import files

files.download("Titanic-Dataset.csv")

import pandas as pd

CSV_PATH = "Titanic-Dataset.csv"

df = pd.read_csv(CSV_PATH)

df.columns = df.columns.str.strip()

print("FIRST 5 ROWS")
display(df.head())

print("\nDATASET SHAPE")
print(df.shape)

print("\nCOLUMN NAMES")
print(df.columns.tolist())

print("\nDATA TYPES")
print(df.dtypes)

print("\nDATASET INFORMATION")
df.info()

print("\nSTATISTICAL SUMMARY")
display(df.describe(include="all"))

print("\nMISSING VALUES")
print(df.isnull().sum())

print("\nDUPLICATE ROWS")
print(df.duplicated().sum())

print("\nSURVIVED DISTRIBUTION")
print(df["survived"].value_counts())

print("\nSURVIVED PERCENTAGE")
print(df["survived"].value_counts(normalize=True) * 100)